export const FULL_SEED_ACCOUNTS = [
  // 100 ACTIVO
  { code: "100", name: "Activo", type: "ACTIVO", nature: "DEUDORA", level: 1, parentCode: null },
  { code: "101", name: "Caja", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "102", name: "Bancos", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "103", name: "Inversiones", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "104", name: "Otros instrumentos financieros", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "105", name: "Clientes", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "106", name: "Cuentas y documentos por cobrar a corto plazo", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "107", name: "Deudores diversos", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "108", name: "Estimación de cuentas incobrables", type: "ACTIVO", nature: "ACREEDORA", level: 2, parentCode: "100" },
  { code: "109", name: "Pagos anticipados", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "110", name: "Subsidio al empleo por aplicar", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "111", name: "Crédito al salario por aplicar", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "112", name: "Impuestos a favor", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "113", name: "Pagos provisionales", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "114", name: "Impuestos retenidos", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "115", name: "Inventario", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "118", name: "Impuestos acreditables pagados", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "119", name: "Impuestos acreditables por pagar", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "120", name: "Anticipo a proveedores", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "151", name: "Terrenos", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "152", name: "Edificios", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "153", name: "Maquinaria y equipo", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "154", name: "Automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "155", name: "Mobiliario y equipo de oficina", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "156", name: "Equipo de cómputo", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "157", name: "Equipo de comunicación", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "158", name: "Activos biológicos, vegetales y animales", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "159", name: "Obras en proceso de activos fijos", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "160", name: "Otros activos fijos", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "161", name: "Ferrocarriles", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "162", name: "Embarcaciones", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "163", name: "Aviones", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "164", name: "Troqueles, moldes, matrices y herramental", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "165", name: "Equipo de comunicaciones telefónicas", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "166", name: "Equipo de comunicación satelital", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "167", name: "Equipo de adaptaciones para personas con capacidades diferentes", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "168", name: "Maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "169", name: "Bicicletas convencionales, bicicletas y motocicletas cuya propulsión sea a través de baterías eléctricas recargables", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "170", name: "Depreciación acumulada de activos fijos", type: "ACTIVO", nature: "ACREEDORA", level: 2, parentCode: "100" },
  { code: "171", name: "Pérdida por deterioro acumulado de activos fijos", type: "ACTIVO", nature: "ACREEDORA", level: 2, parentCode: "100" },
  { code: "172", name: "Gastos preoperativos", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "173", name: "Gastos de organización y de constitución", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "174", name: "Gastos de investigación y desarrollo", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },
  { code: "175", name: "Software e intangibles", type: "ACTIVO", nature: "DEUDORA", level: 2, parentCode: "100" },

  // 200 PASIVO
  { code: "200", name: "Pasivo", type: "PASIVO", nature: "ACREEDORA", level: 1, parentCode: null },
  { code: "201", name: "Proveedores", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "202", name: "Cuentas por pagar a corto plazo", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "203", name: "Cobros anticipados a corto plazo", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "204", name: "Instrumentos financieros a corto plazo", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "205", name: "Acreedores diversos a corto plazo", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "206", name: "Anticipo de clientes", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "207", name: "Impuestos trasladados", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "208", name: "Impuestos trasladados cobrados", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "209", name: "Impuestos trasladados no cobrados", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "210", name: "Provisión de sueldos y salarios por pagar", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "211", name: "Provisión de contribuciones de seguridad social por pagar", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "212", name: "Provisión de impuesto estatal sobre nómina por pagar", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "213", name: "Impuestos y derechos por pagar", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "214", name: "Provisiones por pagar a corto plazo", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },
  { code: "215", name: "Impuestos retenidos", type: "PASIVO", nature: "ACREEDORA", level: 2, parentCode: "200" },

  // 300 CAPITAL CONTABLE
  { code: "300", name: "Capital Contable", type: "CAPITAL", nature: "ACREEDORA", level: 1, parentCode: null },
  { code: "301", name: "Capital social", type: "CAPITAL", nature: "ACREEDORA", level: 2, parentCode: "300" },
  { code: "302", name: "Patrimonio", type: "CAPITAL", nature: "ACREEDORA", level: 2, parentCode: "300" },
  { code: "303", name: "Reserva legal", type: "CAPITAL", nature: "ACREEDORA", level: 2, parentCode: "300" },
  { code: "304", name: "Resultados de ejercicios anteriores", type: "CAPITAL", nature: "ACREEDORA", level: 2, parentCode: "300" },
  { code: "305", name: "Resultado del ejercicio", type: "CAPITAL", nature: "ACREEDORA", level: 2, parentCode: "300" },
  { code: "306", name: "Otras cuentas de capital", type: "CAPITAL", nature: "ACREEDORA", level: 2, parentCode: "300" },

  // 400 INGRESOS
  { code: "400", name: "Ingresos", type: "INGRESOS", nature: "ACREEDORA", level: 1, parentCode: null },
  { code: "401", name: "Ingresos netos por ventas y/o servicios", type: "INGRESOS", nature: "ACREEDORA", level: 2, parentCode: "400" },
  { code: "402", name: "Ingresos por ventas de bienes y servicios (Sector Financiero)", type: "INGRESOS", nature: "ACREEDORA", level: 2, parentCode: "400" },
  { code: "403", name: "Otros ingresos", type: "INGRESOS", nature: "ACREEDORA", level: 2, parentCode: "400" },

  // 500 COSTOS
  { code: "500", name: "Costos", type: "COSTOS", nature: "DEUDORA", level: 1, parentCode: null },
  { code: "501", name: "Costo de venta y/o de servicios", type: "COSTOS", nature: "DEUDORA", level: 2, parentCode: "500" },
  { code: "502", name: "Compras", type: "COSTOS", nature: "DEUDORA", level: 2, parentCode: "500" },
  { code: "503", name: "Devoluciones, descuentos o rebajas sobre compras", type: "COSTOS", nature: "ACREEDORA", level: 2, parentCode: "500" },
  { code: "504", name: "Gastos de compra", type: "COSTOS", nature: "DEUDORA", level: 2, parentCode: "500" },

  // 600 GASTOS
  { code: "600", name: "Gastos", type: "GASTOS", nature: "DEUDORA", level: 1, parentCode: null },
  { code: "601", name: "Gastos generales", type: "GASTOS", nature: "DEUDORA", level: 2, parentCode: "600" },
  { code: "602", name: "Gastos de venta", type: "GASTOS", nature: "DEUDORA", level: 2, parentCode: "600" },
  { code: "603", name: "Gastos de administración", type: "GASTOS", nature: "DEUDORA", level: 2, parentCode: "600" },
  { code: "604", name: "Gastos de fabricación", type: "GASTOS", nature: "DEUDORA", level: 2, parentCode: "600" },
  { code: "605", name: "Mano de obra directa", type: "GASTOS", nature: "DEUDORA", level: 2, parentCode: "600" },
  { code: "606", name: "Facilidades administrativas", type: "GASTOS", nature: "DEUDORA", level: 2, parentCode: "600" },
  
  // 700 RESULTADO INTEGRAL DE FINANCIAMIENTO
  { code: "700", name: "Resultado Integral de Financiamiento", type: "GASTOS", nature: "DEUDORA", level: 1, parentCode: null },
  { code: "701", name: "Gastos financieros", type: "GASTOS", nature: "DEUDORA", level: 2, parentCode: "700" },
  { code: "702", name: "Productos financieros", type: "INGRESOS", nature: "ACREEDORA", level: 2, parentCode: "700" },
  { code: "703", name: "Otros gastos", type: "GASTOS", nature: "DEUDORA", level: 2, parentCode: "700" },
  { code: "704", name: "Otros productos", type: "INGRESOS", nature: "ACREEDORA", level: 2, parentCode: "700" }
];
